name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        node-version: [18.x, 20.x]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: angular-sns-frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd angular-sns-frontend
        npm ci
        
    - name: Build application
      run: |
        cd angular-sns-frontend
        npm run build:prod
        
    - name: Start application server
      run: |
        cd angular-sns-frontend
        npm start &
        sleep 10
        
    - name: Wait for application to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:4200; do sleep 2; done'
        
    - name: Run E2E tests - ${{ matrix.browser }}
      run: |
        cd angular-sns-frontend
        npm run e2e:${{ matrix.browser }}
      env:
        CYPRESS_baseUrl: http://localhost:4200
        CYPRESS_apiUrl: ${{ secrets.API_URL || 'http://localhost:3000/dev' }}
        CYPRESS_apiKey: ${{ secrets.API_KEY || 'dev-api-key' }}
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-results-${{ matrix.browser }}-node${{ matrix.node-version }}
        path: |
          angular-sns-frontend/cypress/screenshots/
          angular-sns-frontend/cypress/videos/
          angular-sns-frontend/cypress/reports/
        retention-days: 30
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-${{ matrix.browser }}-node${{ matrix.node-version }}
        path: angular-sns-frontend/coverage/
        retention-days: 7

  cross-browser-summary:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: angular-sns-frontend/package-lock.json
        
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: test-results/
        
    - name: Generate cross-browser summary
      run: |
        cd angular-sns-frontend
        node cypress/scripts/generate-summary.js ../test-results/
        
    - name: Upload summary report
      uses: actions/upload-artifact@v4
      with:
        name: cross-browser-summary
        path: angular-sns-frontend/cypress/reports/summary.html
        retention-days: 30

  performance-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: angular-sns-frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd angular-sns-frontend
        npm ci
        
    - name: Build application
      run: |
        cd angular-sns-frontend
        npm run build:prod
        
    - name: Start application server
      run: |
        cd angular-sns-frontend
        npm start &
        sleep 10
        
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-results
        path: .lighthouseci/
        retention-days: 30

  accessibility-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: angular-sns-frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd angular-sns-frontend
        npm ci
        npm install -g @axe-core/cli
        
    - name: Build application
      run: |
        cd angular-sns-frontend
        npm run build:prod
        
    - name: Start application server
      run: |
        cd angular-sns-frontend
        npm start &
        sleep 10
        
    - name: Run accessibility tests
      run: |
        axe http://localhost:4200 --exit
        
    - name: Run Cypress accessibility tests
      run: |
        cd angular-sns-frontend
        npm install cypress-axe
        npx cypress run --spec "cypress/e2e/**/accessibility.cy.ts"
        
    - name: Upload accessibility results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: accessibility-results
        path: |
          angular-sns-frontend/cypress/screenshots/
          angular-sns-frontend/cypress/videos/
        retention-days: 30